# Pandas

Материалы:
* Макрушин С.В. "Лекция 2: Библиотека Pandas"
* https://pandas.pydata.org/docs/user_guide/index.html#
* https://pandas.pydata.org/docs/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

1. Загрузите данные из файла `sp500hst.txt` и обозначьте столбцы в соответствии с содержимым: `"date", "ticker", "open", "high", "low", "close", "volume"`.

2. Рассчитайте среднее значение показателей для каждого из столбцов c номерами 3-6.

3. Добавьте столбец, содержащий только число месяца, к которому относится дата.

4. Рассчитайте суммарный объем торгов для для одинаковых значений тикеров.

5. Загрузите данные из файла sp500hst.txt и обозначьте столбцы в соответствии с содержимым: "date", "ticker", "open", "high", "low", "close", "volume". Добавьте столбец с расшифровкой названия тикера, используя данные из файла `sp_data2.csv` . В случае нехватки данных об именах тикеров корректно обработать их.

## Лабораторная работа №2

### Базовые операции с `DataFrame`

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.options.display.max_rows = 10

1.1 В файлах `recipes_sample.csv` и `reviews_sample.csv` находится информация об рецептах блюд и отзывах на эти рецепты соответственно. Загрузите данные из файлов в виде `pd.DataFrame` с названиями `recipes` и `reviews`. Обратите внимание на корректное считывание столбца с индексами в таблице `reviews` (безымянный столбец).

In [4]:
recipes = pd.read_csv('02_pandas/sem/data/recipes_sample.csv', index_col = 'id')

In [5]:
recipes

,name,minutes,contributor_id,submitted,n_steps,description,n_ingredients
id,,,,,,,
44123,george s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
67664,healthy for them yogurt popsicles,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
38798,i can t believe it s spinach,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
35173,italian gut busters,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
84797,love is in the air beef fondue sauces,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...
267661,zurie s holey rustic olive and cheddar bread,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
386977,zwetschgenkuchen bavarian plum cake,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
103312,zwiebelkuchen southwest german onion cake,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
486161,zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN
298512,cookies by design cookies on a stick,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

In [7]:
reviews = pd.read_csv('02_pandas/sem/data/reviews_sample.csv', index_col = [0])

In [8]:
reviews

,user_id,recipe_id,date,rating,review
370476,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
624300,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...
187037,400708,252013,2008-01-10,4,"Very nice breakfast HH, easy to make and yummy..."
706134,2001852463,404716,2017-12-11,5,These are a favorite for the holidays and so e...
312179,95810,129396,2008-03-14,5,Excellent soup! The tomato flavor is just gre...
...,...,...,...,...,...
1013457,1270706,335534,2009-05-17,4,This recipe was great! I made it last night. I...
158736,2282344,8701,2012-06-03,0,This recipe is outstanding. I followed the rec...
1059834,689540,222001,2008-04-08,5,"Well, we were not a crowd but it was a fabulou..."
453285,2000242659,354979,2015-06-02,5,I have been a steak eater and dedicated BBQ gr...
691207,463435,415599,2010-09-30,5,Wonderful and simple to prepare seasoning blen...

1.2 Для каждой из таблиц выведите основные параметры:
* количество точек данных (строк);
* количество столбцов;
* тип данных каждого столбца.

In [9]:
print(recipes.shape)
print(recipes.dtypes)
print('==========================')
print(reviews.shape)
print(reviews.dtypes)

(30000, 7)
name               object
minutes             int64
contributor_id      int64
submitted          object
n_steps           float64
description        object
n_ingredients     float64
dtype: object
==========================
(126696, 5)
user_id       int64
recipe_id     int64
date         object
rating        int64
review       object
dtype: object

1.3 Исследуйте, в каких столбцах таблиц содержатся пропуски. Посчитайте долю строк, содержащих пропуски, в отношении к общему количеству строк.

In [10]:
recNan = recipes.isnull().sum().to_frame()
recNan

                    0
name                0
minutes             0
contributor_id      0
submitted           0
n_steps         11190
description       623
n_ingredients    8880

In [11]:
recNan['a'] = recNan[0]/recipes.shape[0] * 100
recNan

                    0          a
name                0   0.000000
minutes             0   0.000000
contributor_id      0   0.000000
submitted           0   0.000000
n_steps         11190  37.300000
description       623   2.076667
n_ingredients    8880  29.600000

In [12]:
revNan = reviews.isnull().sum().to_frame()
revNan

            0
user_id     0
recipe_id   0
date        0
rating      0
review     17

In [13]:
revNan['a'] = revNan[0]/reviews.shape[0] * 100
revNan

            0         a
user_id     0  0.000000
recipe_id   0  0.000000
date        0  0.000000
rating      0  0.000000
review     17  0.013418

1.4 Рассчитайте среднее значение для каждого из числовых столбцов (где это имеет смысл).

In [14]:
print(recipes['minutes'].mean())
print(recipes['n_ingredients'].mean())
print(recipes['n_steps'].mean())
print(reviews['rating'].mean())

123.35813333333333
9.008285984848484
9.805582137161085
4.410802235271832

1.5 Создайте серию из 10 случайных названий рецептов.

In [15]:
recipes['name'].sample(10).to_frame()

                                                  name
id
116542                      caramel chicken with herbs
63116                         pepper steak in a packet
281731                   mushroom quesadillas  healthy
99823        chocolate spoon cake with cognac cherries
279144  healthy  low fat breakfast sandwich  on the go
408262                        ham hocks and lima beans
340594       casbah chicken   couscous   pampered chef
293879          pizza escarole  escarole pie   italian
413711                         country ham cheese ball
16385                                   pasta dough  1

1.6 Измените индекс в таблице `reviews`, пронумеровав строки, начиная с нуля.

In [16]:
reviews.reset_index()

,index,user_id,recipe_id,date,rating,review
0,370476,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
1,624300,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...
2,187037,400708,252013,2008-01-10,4,"Very nice breakfast HH, easy to make and yummy..."
3,706134,2001852463,404716,2017-12-11,5,These are a favorite for the holidays and so e...
4,312179,95810,129396,2008-03-14,5,Excellent soup! The tomato flavor is just gre...
...,...,...,...,...,...,...
126691,1013457,1270706,335534,2009-05-17,4,This recipe was great! I made it last night. I...
126692,158736,2282344,8701,2012-06-03,0,This recipe is outstanding. I followed the rec...
126693,1059834,689540,222001,2008-04-08,5,"Well, we were not a crowd but it was a fabulou..."
126694,453285,2000242659,354979,2015-06-02,5,I have been a steak eater and dedicated BBQ gr...
126695,691207,463435,415599,2010-09-30,5,Wonderful and simple to prepare seasoning blen...

1.7 Выведите информацию о рецептах, время выполнения которых не больше 20 минут и кол-во ингредиентов в которых не больше 5.

In [17]:
recipes[(recipes['minutes'] <= 20) & (recipes['n_ingredients'] <= 5)]

,name,minutes,contributor_id,submitted,n_steps,description,n_ingredients
id,,,,,,,
302399,quick biscuit bread,20,213909,2008-05-06,11.0,this is a wonderful quick bread to make as an ...,5.0
303944,peas fit for a king or queen,20,213909,2008-05-16,NaN,this recipe is so simple and the flavors are s...,5.0
100837,hawaiian sunrise mimosa,5,58104,2004-09-29,4.0,pineapple mimosa was changed to hawaiian sunri...,3.0
286484,tasty dish s banana pudding in 2 minutes,2,47892,2008-02-13,NaN,"""mmmm, i love bananas!"" a --tasty dish-- origi...",4.0
11361,1 minute meatballs,13,4470,2001-09-03,NaN,this is a real short cut for cooks in a hurry....,2.0
...,...,...,...,...,...,...,...
304922,zip and steam red potatoes with butter and garlic,13,724218,2008-05-27,9.0,"i haven't tried this yet, but i am going to so...",5.0
74250,ziplock vanilla ice cream,10,24386,2003-10-29,8.0,a fun thing for kids to do. may want to use mi...,3.0
256177,zucchini and corn with cheese,15,305531,2007-09-29,4.0,from betty crocker fresh spring recipes. i lik...,5.0
320622,zucchini with jalapeno monterey jack,10,305531,2008-08-20,3.0,simple and yummy!,3.0
162411,zucchini with serrano ham,15,152500,2006-03-31,6.0,"this dish is from tim malzer, a german chef wh...",5.0

### Работа с датами в `pandas`

2.1 Преобразуйте столбец `submitted` из таблицы `recipes` в формат времени. Модифицируйте решение задачи 1.1 так, чтобы считать столбец сразу в нужном формате.

In [19]:
recipesDT = pd.read_csv('02_pandas/sem/data/recipes_sample.csv', index_col = 'id', parse_dates = ['submitted'])

In [20]:
recipesDT.dtypes

name                      object
minutes                    int64
contributor_id             int64
submitted         datetime64[ns]
n_steps                  float64
description               object
n_ingredients            float64
dtype: object

2.2 Выведите информацию о рецептах, добавленных в датасет не позже 2010 года.

In [20]:
recipesDT[recipesDT['submitted'] <= '2010-01-01']

,name,minutes,contributor_id,submitted,n_steps,description,n_ingredients
id,,,,,,,
44123,george s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
67664,healthy for them yogurt popsicles,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
38798,i can t believe it s spinach,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
35173,italian gut busters,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
84797,love is in the air beef fondue sauces,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
44045,mennonite corn fritters,15,41706,2002-10-25,NaN,ok - my heritage has been revealed. :) these a...,NaN
107229,open sesame noodles,28,173674,2004-12-30,8.0,this is a very versatile and widely enjoyed pa...,12.0
95926,say what banana sandwich,5,118163,2004-07-20,4.0,you just have to try it to believe it.,NaN
306168,412 broccoli casserole,40,50969,2008-05-30,6.0,since there are already 411 recipes for brocco...,NaN
50662,25 000 casserole,125,9748,2003-01-10,NaN,this is a recipe that my mother got from some ...,NaN
118843,250 00 chocolate chip cookies,20,145599,2005-04-24,NaN,these are great! the perfect name for them!,13.0
69190,ara s potato oup,135,98404,2003-08-20,5.0,i made this recipe myself when i was 13. i was...,NaN
149593,add in anything muffins,15,89831,2005-12-28,NaN,"this is a never-fail muffin recipe, it's a bla...",9.0
200148,better than tofu cheesecake,90,261027,2006-12-11,18.0,"this is, again, from vegweb.com. this got abso...",13.0
310570,burek or feta cheese phyllo pie,65,676820,2008-06-24,38.0,"ok, there are different version of burek (some...",6.0
95534,da best chicago style italian beef,645,94272,2004-07-13,NaN,"tender, garlicky and full of oregano 'n stuff!...",NaN
109818,german barbecued carrots,55,64918,2005-01-28,NaN,this is something my grandma made at christmas...,NaN
66932,healthy fried rice,25,93406,2003-07-16,NaN,"i made this once, hoping to have something lig...",8.0
226001,i can t believe i made cream puffs,55,237783,2007-05-02,NaN,my old friend pat gave me this recipe 20 years...,6.0
125195,kelly s creamy cheddar pea salad,20,113941,2005-06-09,5.0,"i'm not a big fan of peas, but like them in th...",10.0
141939,kicked up oven fried chicken,345,89831,2005-10-19,13.0,i make mine on one cookie rack placed on a bak...,17.0
250883,margarita dip for fresh or grilled fruit,70,398160,2007-09-04,14.0,this cool and creamy dip is a refreshing treat...,4.0
120297,middle eastern twice baked potatoes,110,197023,2005-05-02,14.0,a delicious yet low-fat twice-baked potato sid...,10.0
147477,pass me another hot clam dip,15,135442,2005-12-05,3.0,this recipe is from an appetizer book that i i...,7.0
223349,pasta with shrimp eggplant,50,452592,2007-04-18,7.0,a nice low carb way to feel like you are eatin...,9.0
60938,pizza pan potato skins,60,35635,2003-04-24,NaN,there's a pub we go to that makes their own fr...,7.0
302399,quick biscuit bread,20,213909,2008-05-06,11.0,this is a wonderful quick bread to make as an ...,5.0
342620,secret ingredient bbq meatloaf,75,50969,2008-12-09,9.0,"i know what you might be thinking,'ho hum, ano...",10.0
296983,skordy new potatoes w rosemary lemon olive oi,35,718054,2008-04-08,NaN,i took this recipe from a vegan tastes of gree...,6.0
166089,sticky chicky dump chicken,55,290107,2006-04-27,14.0,i found this recipe online. the idea here is t...,5.0
...,...,...,...,...,...,...,...
130124,zucchini sausage lasagna,80,152995,2005-07-18,13.0,this is from taste of home. my family absolute...,17.0
80067,zucchini spice cake,65,4439,2004-01-02,11.0,"this recipe is pretty close to bizzare, but it...",4.0
324642,zucchini spice muffins,35,613544,2008-09-11,NaN,from robin hood home baking cookbook. these fr...,11.0
279769,zucchini strips,30,522304,2008-01-18,8.0,"spicy, salty, crispy zucchini strips!",4.0
72857,zucchini stuffed with feta and basil,30,95743,2003-10-08,NaN,"easy to make, savory and a nice presentation. ...",5.0
130447,zucchini stuffed with goat cheese and mint,30,182809,2005-07-19,14.0,this was past on to me by a gentleman friend w...,10.0
378799,zucchini tart with gruyere cheese and herbs,35,177443,2009-06-24,16.0,"this tart is wonderful picnic, potluck or part...",11.0
335783,zucchini tarte with bacon,80,930100,2008-11-08,10.0,this is another recipe from mark bittman's coo...,NaN
321224,zucchini tomato salsa,20,464080,2008-08-25,4.0,a contest winner from taste of home. it state...,13.0
41095,zucchini tomato toss,15,47579,2002-09-24,3.0,i tried a similar recipe but altered most of i...,10.0
174719,zucchini wheat germ cookies,30,135870,2006-06-26,7.0,since i have an abundance of zucchini in my ga...,14.0
326105,zucchini with bacon corn peppers,45,896136,2008-09-19,8.0,this is a very colorful addition to any meal. ...,7.0
363362,zucchini with bell pepper and tomato,13,344321,2009-03-29,19.0,the weather has been turning warmer and i have...,8.0
320622,zucchini with jalapeno monterey jack,10,305531,2008-08-20,3.0,simple and yummy!,3.0
96162,zucchini with pasta,30,125388,2004-07-22,NaN,you can never have too many zucchini recipes. ...,9.0
34481,zucchini with pesto sauce,41,4470,2002-07-17,8.0,if you are not fond of basil substitute with s...,NaN
162411,zucchini with serrano ham,15,152500,2006-03-31,6.0,"this dish is from tim malzer, a german chef wh...",5.0
36349,zucchini corn black bean and jack cheese qu...,30,3288,2002-08-05,NaN,one of those email recipes i haven't tried yet...,11.0
325574,zucchini pineapple ginger jam kicked up with...,50,58104,2008-09-18,15.0,i came up with this sweet and spicy jam after ...,8.0
344542,zucchini potato and herb fritters,30,197023,2008-12-21,8.0,adapted from a recipe in 'the australian women...,12.0
112591,zucchini carrot cake with cream cheese frosting,80,176348,2005-03-03,NaN,this recipe is good to have around when zucchi...,15.0
287490,zucchini carrot muffins,40,227586,2008-02-21,NaN,"got this recipe from from family circle, march...",13.0
74023,zucchini cheddar casserole,50,89831,2003-10-24,14.0,this has been a long time family favorite!,8.0
71450,zucchini pineapple loaf cake,70,89831,2003-09-15,NaN,i got this recipe from a local paper a long ti...,NaN
180833,zucchini potato pancakes,45,186118,2006-08-07,NaN,"this recipe was posted in our local newspaper,...",9.0
316950,zuni caf zucchini pickles,2895,62264,2008-07-31,NaN,refrigerator pickles for some of the zucchini ...,8.0
267661,zurie s holey rustic olive and cheddar bread,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
386977,zwetschgenkuchen bavarian plum cake,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
103312,zwiebelkuchen southwest german onion cake,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
298512,cookies by design cookies on a stick,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

### Работа со строковыми данными в `pandas`

3.1  Добавьте в таблицу `recipes` столбец `description_length`, в котором хранится длина описания рецепта из столбца `description`.

In [21]:
recipes['description_length'] = recipes['description'].str.len()

In [22]:
recipes

,name,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length
id,,,,,,,,
44123,george s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0
67664,healthy for them yogurt popsicles,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0
38798,i can t believe it s spinach,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0
35173,italian gut busters,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0
84797,love is in the air beef fondue sauces,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0
44045,mennonite corn fritters,15,41706,2002-10-25,NaN,ok - my heritage has been revealed. :) these a...,NaN,149.0
107229,open sesame noodles,28,173674,2004-12-30,8.0,this is a very versatile and widely enjoyed pa...,12.0,290.0
95926,say what banana sandwich,5,118163,2004-07-20,4.0,you just have to try it to believe it.,NaN,38.0
453467,1 in canada chocolate chip cookies,45,1848091,2011-04-11,12.0,this is the recipe that we use at my school ca...,11.0,230.0
306168,412 broccoli casserole,40,50969,2008-05-30,6.0,since there are already 411 recipes for brocco...,NaN,369.0
50662,25 000 casserole,125,9748,2003-01-10,NaN,this is a recipe that my mother got from some ...,NaN,294.0
118843,250 00 chocolate chip cookies,20,145599,2005-04-24,NaN,these are great! the perfect name for them!,13.0,43.0
69190,ara s potato oup,135,98404,2003-08-20,5.0,i made this recipe myself when i was 13. i was...,NaN,315.0
503475,blepandekager danish apple pancakes,50,128473,2013-07-08,10.0,this recipe has been posted here for play in z...,NaN,144.0
149593,add in anything muffins,15,89831,2005-12-28,NaN,"this is a never-fail muffin recipe, it's a bla...",9.0,240.0
200148,better than tofu cheesecake,90,261027,2006-12-11,18.0,"this is, again, from vegweb.com. this got abso...",13.0,380.0
310570,burek or feta cheese phyllo pie,65,676820,2008-06-24,38.0,"ok, there are different version of burek (some...",6.0,556.0
95534,da best chicago style italian beef,645,94272,2004-07-13,NaN,"tender, garlicky and full of oregano 'n stuff!...",NaN,463.0
109818,german barbecued carrots,55,64918,2005-01-28,NaN,this is something my grandma made at christmas...,NaN,385.0
66932,healthy fried rice,25,93406,2003-07-16,NaN,"i made this once, hoping to have something lig...",8.0,151.0
226001,i can t believe i made cream puffs,55,237783,2007-05-02,NaN,my old friend pat gave me this recipe 20 years...,6.0,132.0
125195,kelly s creamy cheddar pea salad,20,113941,2005-06-09,5.0,"i'm not a big fan of peas, but like them in th...",10.0,102.0
141939,kicked up oven fried chicken,345,89831,2005-10-19,13.0,i make mine on one cookie rack placed on a bak...,17.0,544.0
250883,margarita dip for fresh or grilled fruit,70,398160,2007-09-04,14.0,this cool and creamy dip is a refreshing treat...,4.0,134.0
120297,middle eastern twice baked potatoes,110,197023,2005-05-02,14.0,a delicious yet low-fat twice-baked potato sid...,10.0,551.0
147477,pass me another hot clam dip,15,135442,2005-12-05,3.0,this recipe is from an appetizer book that i i...,7.0,144.0
223349,pasta with shrimp eggplant,50,452592,2007-04-18,7.0,a nice low carb way to feel like you are eatin...,9.0,54.0
60938,pizza pan potato skins,60,35635,2003-04-24,NaN,there's a pub we go to that makes their own fr...,7.0,371.0
302399,quick biscuit bread,20,213909,2008-05-06,11.0,this is a wonderful quick bread to make as an ...,5.0,117.0
342620,secret ingredient bbq meatloaf,75,50969,2008-12-09,9.0,"i know what you might be thinking,'ho hum, ano...",10.0,326.0
...,...,...,...,...,...,...,...,...
72857,zucchini stuffed with feta and basil,30,95743,2003-10-08,NaN,"easy to make, savory and a nice presentation. ...",5.0,113.0
130447,zucchini stuffed with goat cheese and mint,30,182809,2005-07-19,14.0,this was past on to me by a gentleman friend w...,10.0,64.0
378799,zucchini tart with gruyere cheese and herbs,35,177443,2009-06-24,16.0,"this tart is wonderful picnic, potluck or part...",11.0,446.0
335783,zucchini tarte with bacon,80,930100,2008-11-08,10.0,this is another recipe from mark bittman's coo...,NaN,199.0
321224,zucchini tomato salsa,20,464080,2008-08-25,4.0,a contest winner from taste of home. it state...,13.0,285.0
41095,zucchini tomato toss,15,47579,2002-09-24,3.0,i tried a similar recipe but altered most of i...,10.0,133.0
505053,zucchini tots,20,798181,2013-07-31,NaN,'the happy homemaker blog' shared this recipe ...,NaN,122.0
174719,zucchini wheat germ cookies,30,135870,2006-06-26,7.0,since i have an abundance of zucchini in my ga...,14.0,212.0
326105,zucchini with bacon corn peppers,45,896136,2008-09-19,8.0,this is a very colorful addition to any meal. ...,7.0,253.0
363362,zucchini with bell pepper and tomato,13,344321,2009-03-29,19.0,the weather has been turning warmer and i have...,8.0,319.0
320622,zucchini with jalapeno monterey jack,10,305531,2008-08-20,3.0,simple and yummy!,3.0,17.0
96162,zucchini with pasta,30,125388,2004-07-22,NaN,you can never have too many zucchini recipes. ...,9.0,114.0
34481,zucchini with pesto sauce,41,4470,2002-07-17,8.0,if you are not fond of basil substitute with s...,NaN,100.0
162411,zucchini with serrano ham,15,152500,2006-03-31,6.0,"this dish is from tim malzer, a german chef wh...",5.0,136.0
36349,zucchini corn black bean and jack cheese qu...,30,3288,2002-08-05,NaN,one of those email recipes i haven't tried yet...,11.0,157.0
325574,zucchini pineapple ginger jam kicked up with...,50,58104,2008-09-18,15.0,i came up with this sweet and spicy jam after ...,8.0,261.0
344542,zucchini potato and herb fritters,30,197023,2008-12-21,8.0,adapted from a recipe in 'the australian women...,12.0,888.0
112591,zucchini carrot cake with cream cheese frosting,80,176348,2005-03-03,NaN,this recipe is good to have around when zucchi...,15.0,184.0
287490,zucchini carrot muffins,40,227586,2008-02-21,NaN,"got this recipe from from family circle, march...",13.0,116.0
74023,zucchini cheddar casserole,50,89831,2003-10-24,14.0,this has been a long time family favorite!,8.0,42.0
71450,zucchini pineapple loaf cake,70,89831,2003-09-15,NaN,i got this recipe from a local paper a long ti...,NaN,275.0
180833,zucchini potato pancakes,45,186118,2006-08-07,NaN,"this recipe was posted in our local newspaper,...",9.0,242.0
415406,zucchini courgette soup good for weight watc...,45,485109,2010-03-04,5.0,this is a favourite winter warmer. by british ...,NaN,135.0
316950,zuni caf zucchini pickles,2895,62264,2008-07-31,NaN,refrigerator pickles for some of the zucchini ...,8.0,298.0
464576,zuppa by luisa,70,226863,2011-09-20,14.0,this soup is a hearty meal! from luisa musso.,17.0,46.0
267661,zurie s holey rustic olive and cheddar bread,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0,484.0
386977,zwetschgenkuchen bavarian plum cake,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0,286.0
103312,zwiebelkuchen southwest german onion cake,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN,311.0
486161,zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,648.0
298512,cookies by design cookies on a stick,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0,125.0

3.2 Измените название каждого рецепта в таблице `recipes` таким образом, чтобы каждое слово в названии начиналось с прописной буквы.

In [23]:
recipes['name'] = recipes['name'].str.capitalize()

In [24]:
recipes

,name,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length
id,,,,,,,,
44123,George s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0
67664,Healthy for them yogurt popsicles,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0
38798,I can t believe it s spinach,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0
35173,Italian gut busters,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0
84797,Love is in the air beef fondue sauces,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0
44045,Mennonite corn fritters,15,41706,2002-10-25,NaN,ok - my heritage has been revealed. :) these a...,NaN,149.0
107229,Open sesame noodles,28,173674,2004-12-30,8.0,this is a very versatile and widely enjoyed pa...,12.0,290.0
95926,Say what banana sandwich,5,118163,2004-07-20,4.0,you just have to try it to believe it.,NaN,38.0
453467,1 in canada chocolate chip cookies,45,1848091,2011-04-11,12.0,this is the recipe that we use at my school ca...,11.0,230.0
306168,412 broccoli casserole,40,50969,2008-05-30,6.0,since there are already 411 recipes for brocco...,NaN,369.0
50662,25 000 casserole,125,9748,2003-01-10,NaN,this is a recipe that my mother got from some ...,NaN,294.0
118843,250 00 chocolate chip cookies,20,145599,2005-04-24,NaN,these are great! the perfect name for them!,13.0,43.0
69190,Ara s potato oup,135,98404,2003-08-20,5.0,i made this recipe myself when i was 13. i was...,NaN,315.0
503475,Blepandekager danish apple pancakes,50,128473,2013-07-08,10.0,this recipe has been posted here for play in z...,NaN,144.0
149593,Add in anything muffins,15,89831,2005-12-28,NaN,"this is a never-fail muffin recipe, it's a bla...",9.0,240.0
200148,Better than tofu cheesecake,90,261027,2006-12-11,18.0,"this is, again, from vegweb.com. this got abso...",13.0,380.0
310570,Burek or feta cheese phyllo pie,65,676820,2008-06-24,38.0,"ok, there are different version of burek (some...",6.0,556.0
95534,Da best chicago style italian beef,645,94272,2004-07-13,NaN,"tender, garlicky and full of oregano 'n stuff!...",NaN,463.0
109818,German barbecued carrots,55,64918,2005-01-28,NaN,this is something my grandma made at christmas...,NaN,385.0
66932,Healthy fried rice,25,93406,2003-07-16,NaN,"i made this once, hoping to have something lig...",8.0,151.0
226001,I can t believe i made cream puffs,55,237783,2007-05-02,NaN,my old friend pat gave me this recipe 20 years...,6.0,132.0
125195,Kelly s creamy cheddar pea salad,20,113941,2005-06-09,5.0,"i'm not a big fan of peas, but like them in th...",10.0,102.0
141939,Kicked up oven fried chicken,345,89831,2005-10-19,13.0,i make mine on one cookie rack placed on a bak...,17.0,544.0
250883,Margarita dip for fresh or grilled fruit,70,398160,2007-09-04,14.0,this cool and creamy dip is a refreshing treat...,4.0,134.0
120297,Middle eastern twice baked potatoes,110,197023,2005-05-02,14.0,a delicious yet low-fat twice-baked potato sid...,10.0,551.0
147477,Pass me another hot clam dip,15,135442,2005-12-05,3.0,this recipe is from an appetizer book that i i...,7.0,144.0
223349,Pasta with shrimp eggplant,50,452592,2007-04-18,7.0,a nice low carb way to feel like you are eatin...,9.0,54.0
60938,Pizza pan potato skins,60,35635,2003-04-24,NaN,there's a pub we go to that makes their own fr...,7.0,371.0
302399,Quick biscuit bread,20,213909,2008-05-06,11.0,this is a wonderful quick bread to make as an ...,5.0,117.0
342620,Secret ingredient bbq meatloaf,75,50969,2008-12-09,9.0,"i know what you might be thinking,'ho hum, ano...",10.0,326.0
...,...,...,...,...,...,...,...,...
72857,Zucchini stuffed with feta and basil,30,95743,2003-10-08,NaN,"easy to make, savory and a nice presentation. ...",5.0,113.0
130447,Zucchini stuffed with goat cheese and mint,30,182809,2005-07-19,14.0,this was past on to me by a gentleman friend w...,10.0,64.0
378799,Zucchini tart with gruyere cheese and herbs,35,177443,2009-06-24,16.0,"this tart is wonderful picnic, potluck or part...",11.0,446.0
335783,Zucchini tarte with bacon,80,930100,2008-11-08,10.0,this is another recipe from mark bittman's coo...,NaN,199.0
321224,Zucchini tomato salsa,20,464080,2008-08-25,4.0,a contest winner from taste of home. it state...,13.0,285.0
41095,Zucchini tomato toss,15,47579,2002-09-24,3.0,i tried a similar recipe but altered most of i...,10.0,133.0
505053,Zucchini tots,20,798181,2013-07-31,NaN,'the happy homemaker blog' shared this recipe ...,NaN,122.0
174719,Zucchini wheat germ cookies,30,135870,2006-06-26,7.0,since i have an abundance of zucchini in my ga...,14.0,212.0
326105,Zucchini with bacon corn peppers,45,896136,2008-09-19,8.0,this is a very colorful addition to any meal. ...,7.0,253.0
363362,Zucchini with bell pepper and tomato,13,344321,2009-03-29,19.0,the weather has been turning warmer and i have...,8.0,319.0
320622,Zucchini with jalapeno monterey jack,10,305531,2008-08-20,3.0,simple and yummy!,3.0,17.0
96162,Zucchini with pasta,30,125388,2004-07-22,NaN,you can never have too many zucchini recipes. ...,9.0,114.0
34481,Zucchini with pesto sauce,41,4470,2002-07-17,8.0,if you are not fond of basil substitute with s...,NaN,100.0
162411,Zucchini with serrano ham,15,152500,2006-03-31,6.0,"this dish is from tim malzer, a german chef wh...",5.0,136.0
36349,Zucchini corn black bean and jack cheese qu...,30,3288,2002-08-05,NaN,one of those email recipes i haven't tried yet...,11.0,157.0
325574,Zucchini pineapple ginger jam kicked up with...,50,58104,2008-09-18,15.0,i came up with this sweet and spicy jam after ...,8.0,261.0
344542,Zucchini potato and herb fritters,30,197023,2008-12-21,8.0,adapted from a recipe in 'the australian women...,12.0,888.0
112591,Zucchini carrot cake with cream cheese frosting,80,176348,2005-03-03,NaN,this recipe is good to have around when zucchi...,15.0,184.0
287490,Zucchini carrot muffins,40,227586,2008-02-21,NaN,"got this recipe from from family circle, march...",13.0,116.0
74023,Zucchini cheddar casserole,50,89831,2003-10-24,14.0,this has been a long time family favorite!,8.0,42.0
71450,Zucchini pineapple loaf cake,70,89831,2003-09-15,NaN,i got this recipe from a local paper a long ti...,NaN,275.0
180833,Zucchini potato pancakes,45,186118,2006-08-07,NaN,"this recipe was posted in our local newspaper,...",9.0,242.0
415406,Zucchini courgette soup good for weight watc...,45,485109,2010-03-04,5.0,this is a favourite winter warmer. by british ...,NaN,135.0
316950,Zuni caf zucchini pickles,2895,62264,2008-07-31,NaN,refrigerator pickles for some of the zucchini ...,8.0,298.0
464576,Zuppa by luisa,70,226863,2011-09-20,14.0,this soup is a hearty meal! from luisa musso.,17.0,46.0
267661,Zurie s holey rustic olive and cheddar bread,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0,484.0
386977,Zwetschgenkuchen bavarian plum cake,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0,286.0
103312,Zwiebelkuchen southwest german onion cake,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN,311.0
486161,Zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,648.0
298512,Cookies by design cookies on a stick,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0,125.0

3.3 Добавьте в таблицу `recipes` столбец `name_word_count`, в котором хранится количество слов из названии рецепта (считайте, что слова в названии разделяются только пробелами). Обратите внимание, что между словами может располагаться несколько пробелов подряд.

In [25]:
recipes['name_word_count'] = recipes['name'].str.split().str.len()

In [26]:
recipes

,name,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length,name_word_count
id,,,,,,,,,
44123,George s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0,8
67664,Healthy for them yogurt popsicles,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0,5
38798,I can t believe it s spinach,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0,7
35173,Italian gut busters,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0,3
84797,Love is in the air beef fondue sauces,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0,8
44045,Mennonite corn fritters,15,41706,2002-10-25,NaN,ok - my heritage has been revealed. :) these a...,NaN,149.0,3
107229,Open sesame noodles,28,173674,2004-12-30,8.0,this is a very versatile and widely enjoyed pa...,12.0,290.0,3
95926,Say what banana sandwich,5,118163,2004-07-20,4.0,you just have to try it to believe it.,NaN,38.0,4
453467,1 in canada chocolate chip cookies,45,1848091,2011-04-11,12.0,this is the recipe that we use at my school ca...,11.0,230.0,6
306168,412 broccoli casserole,40,50969,2008-05-30,6.0,since there are already 411 recipes for brocco...,NaN,369.0,3
50662,25 000 casserole,125,9748,2003-01-10,NaN,this is a recipe that my mother got from some ...,NaN,294.0,3
118843,250 00 chocolate chip cookies,20,145599,2005-04-24,NaN,these are great! the perfect name for them!,13.0,43.0,5
69190,Ara s potato oup,135,98404,2003-08-20,5.0,i made this recipe myself when i was 13. i was...,NaN,315.0,4
503475,Blepandekager danish apple pancakes,50,128473,2013-07-08,10.0,this recipe has been posted here for play in z...,NaN,144.0,4
149593,Add in anything muffins,15,89831,2005-12-28,NaN,"this is a never-fail muffin recipe, it's a bla...",9.0,240.0,4
200148,Better than tofu cheesecake,90,261027,2006-12-11,18.0,"this is, again, from vegweb.com. this got abso...",13.0,380.0,4
310570,Burek or feta cheese phyllo pie,65,676820,2008-06-24,38.0,"ok, there are different version of burek (some...",6.0,556.0,6
95534,Da best chicago style italian beef,645,94272,2004-07-13,NaN,"tender, garlicky and full of oregano 'n stuff!...",NaN,463.0,6
109818,German barbecued carrots,55,64918,2005-01-28,NaN,this is something my grandma made at christmas...,NaN,385.0,3
66932,Healthy fried rice,25,93406,2003-07-16,NaN,"i made this once, hoping to have something lig...",8.0,151.0,3
226001,I can t believe i made cream puffs,55,237783,2007-05-02,NaN,my old friend pat gave me this recipe 20 years...,6.0,132.0,8
125195,Kelly s creamy cheddar pea salad,20,113941,2005-06-09,5.0,"i'm not a big fan of peas, but like them in th...",10.0,102.0,6
141939,Kicked up oven fried chicken,345,89831,2005-10-19,13.0,i make mine on one cookie rack placed on a bak...,17.0,544.0,5
250883,Margarita dip for fresh or grilled fruit,70,398160,2007-09-04,14.0,this cool and creamy dip is a refreshing treat...,4.0,134.0,7
120297,Middle eastern twice baked potatoes,110,197023,2005-05-02,14.0,a delicious yet low-fat twice-baked potato sid...,10.0,551.0,5
147477,Pass me another hot clam dip,15,135442,2005-12-05,3.0,this recipe is from an appetizer book that i i...,7.0,144.0,6
223349,Pasta with shrimp eggplant,50,452592,2007-04-18,7.0,a nice low carb way to feel like you are eatin...,9.0,54.0,4
60938,Pizza pan potato skins,60,35635,2003-04-24,NaN,there's a pub we go to that makes their own fr...,7.0,371.0,4
302399,Quick biscuit bread,20,213909,2008-05-06,11.0,this is a wonderful quick bread to make as an ...,5.0,117.0,3
342620,Secret ingredient bbq meatloaf,75,50969,2008-12-09,9.0,"i know what you might be thinking,'ho hum, ano...",10.0,326.0,4
...,...,...,...,...,...,...,...,...,...
72857,Zucchini stuffed with feta and basil,30,95743,2003-10-08,NaN,"easy to make, savory and a nice presentation. ...",5.0,113.0,6
130447,Zucchini stuffed with goat cheese and mint,30,182809,2005-07-19,14.0,this was past on to me by a gentleman friend w...,10.0,64.0,7
378799,Zucchini tart with gruyere cheese and herbs,35,177443,2009-06-24,16.0,"this tart is wonderful picnic, potluck or part...",11.0,446.0,7
335783,Zucchini tarte with bacon,80,930100,2008-11-08,10.0,this is another recipe from mark bittman's coo...,NaN,199.0,4
321224,Zucchini tomato salsa,20,464080,2008-08-25,4.0,a contest winner from taste of home. it state...,13.0,285.0,3
41095,Zucchini tomato toss,15,47579,2002-09-24,3.0,i tried a similar recipe but altered most of i...,10.0,133.0,3
505053,Zucchini tots,20,798181,2013-07-31,NaN,'the happy homemaker blog' shared this recipe ...,NaN,122.0,2
174719,Zucchini wheat germ cookies,30,135870,2006-06-26,7.0,since i have an abundance of zucchini in my ga...,14.0,212.0,4
326105,Zucchini with bacon corn peppers,45,896136,2008-09-19,8.0,this is a very colorful addition to any meal. ...,7.0,253.0,5
363362,Zucchini with bell pepper and tomato,13,344321,2009-03-29,19.0,the weather has been turning warmer and i have...,8.0,319.0,6
320622,Zucchini with jalapeno monterey jack,10,305531,2008-08-20,3.0,simple and yummy!,3.0,17.0,5
96162,Zucchini with pasta,30,125388,2004-07-22,NaN,you can never have too many zucchini recipes. ...,9.0,114.0,3
34481,Zucchini with pesto sauce,41,4470,2002-07-17,8.0,if you are not fond of basil substitute with s...,NaN,100.0,4
162411,Zucchini with serrano ham,15,152500,2006-03-31,6.0,"this dish is from tim malzer, a german chef wh...",5.0,136.0,4
36349,Zucchini corn black bean and jack cheese qu...,30,3288,2002-08-05,NaN,one of those email recipes i haven't tried yet...,11.0,157.0,8
325574,Zucchini pineapple ginger jam kicked up with...,50,58104,2008-09-18,15.0,i came up with this sweet and spicy jam after ...,8.0,261.0,9
344542,Zucchini potato and herb fritters,30,197023,2008-12-21,8.0,adapted from a recipe in 'the australian women...,12.0,888.0,5
112591,Zucchini carrot cake with cream cheese frosting,80,176348,2005-03-03,NaN,this recipe is good to have around when zucchi...,15.0,184.0,7
287490,Zucchini carrot muffins,40,227586,2008-02-21,NaN,"got this recipe from from family circle, march...",13.0,116.0,3
74023,Zucchini cheddar casserole,50,89831,2003-10-24,14.0,this has been a long time family favorite!,8.0,42.0,3
71450,Zucchini pineapple loaf cake,70,89831,2003-09-15,NaN,i got this recipe from a local paper a long ti...,NaN,275.0,4
180833,Zucchini potato pancakes,45,186118,2006-08-07,NaN,"this recipe was posted in our local newspaper,...",9.0,242.0,3
415406,Zucchini courgette soup good for weight watc...,45,485109,2010-03-04,5.0,this is a favourite winter warmer. by british ...,NaN,135.0,7
316950,Zuni caf zucchini pickles,2895,62264,2008-07-31,NaN,refrigerator pickles for some of the zucchini ...,8.0,298.0,4
464576,Zuppa by luisa,70,226863,2011-09-20,14.0,this soup is a hearty meal! from luisa musso.,17.0,46.0,3
267661,Zurie s holey rustic olive and cheddar bread,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0,484.0,8
386977,Zwetschgenkuchen bavarian plum cake,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0,286.0,4
103312,Zwiebelkuchen southwest german onion cake,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN,311.0,5
486161,Zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,648.0,2
298512,Cookies by design cookies on a stick,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0,125.0,7

### Группировки таблиц `pd.DataFrame`

4.1 Посчитайте количество рецептов, представленных каждым из участников (`contributor_id`). Какой участник добавил максимальное кол-во рецептов?

In [38]:
recipes.groupby('contributor_id')['name'].count().to_frame().sort_values(by = 'name', ascending = False)

                name
contributor_id
89831            421
37449            346
37779            345
1533             186
169430           183
58104            180
80353            147
4470             141
283251           127
166642           115
305531           113
27643            109
17803            108
424680           108
37636            105
383346           105
21752            100
5060              99
52282             98
39835             94
64642             93
23302             92
47892             91
68460             90
49304             90
133174            89
386585            89
53959             84
6357              84
24386             82
...              ...
242482             1
242413             1
242201             1
241872             1
241697             1
241696             1
245159             1
245247             1
245280             1
245367             1
247830             1
247780             1
247562             1
247476             1
247473             1
247292             1
247241             1
246520             1
246237             1
246168             1
246162             1
246147             1
246141             1
245993             1
245915             1
245835             1
245653             1
245590             1
245378             1
2002247884         1

[8404 rows x 1 columns]

4.2 Посчитайте средний рейтинг к каждому из рецептов. Для скольких рецептов отсутствуют отзывы? Обратите внимание, что отзыв с нулевым рейтингом или не заполненным текстовым описанием не считается отсутствующим.

In [40]:
reviews.groupby('recipe_id')['rating'].mean()

recipe_id
48        1.000000
55        4.750000
66        4.944444
91        4.750000
94        5.000000
128       5.000000
148       0.000000
153       3.923077
176       5.000000
181       2.666667
186       4.777778
203       4.071429
224       3.000000
240       3.857143
246       4.629630
282       5.000000
284       5.000000
288       2.666667
289       5.000000
314       4.818182
318       4.750000
321       5.000000
337       2.000000
344       2.000000
352       3.750000
360       5.000000
373       5.000000
378       4.625000
379       4.666667
381       5.000000
            ...
534062    0.000000
534064    5.000000
534196    0.000000
534283    5.000000
534393    0.000000
534549    4.000000
534786    5.000000
534855    5.000000
535104    5.000000
535120    5.000000
535269    0.000000
535312    0.000000
535389    5.000000
535555    4.500000
535584    0.000000
535650    5.000000
535691    0.000000
535713    0.000000
535783    3.000000
536051    5.000000
536066    5.000000
536098    4.000000
536212    5.000000
536360    5.000000
536473    5.000000
536547    5.000000
536610    0.000000
536728    4.000000
536729    4.750000
536747    0.000000
Name: rating, Length: 28100, dtype: float64

In [51]:
recipes.reset_index(inplace = True)

In [55]:
recipes['id'].isin(reviews['recipe_id']).value_counts()

True     28100
False     1900
Name: id, dtype: int64

4.3 Посчитайте количество рецептов с разбивкой по годам создания.

In [59]:
recipesDT.groupby(recipesDT['submitted'].dt.year)['name'].count()

submitted
1999     275
2000     104
2001     589
2002    2644
2003    2334
2004    2153
2005    3130
2006    3473
2007    4429
2008    4029
2009    2963
2010    1538
2011     922
2012     659
2013     490
2014     139
2015      42
2016      24
2017      39
2018      24
Name: name, dtype: int64

### Объединение таблиц `pd.DataFrame`

5.1 При помощи объединения таблиц, создайте `DataFrame`, состоящий из четырех столбцов: `id`, `name`, `user_id`, `rating`. Рецепты, на которые не оставлен ни один отзыв, должны отсутствовать в полученной таблице. Подтвердите правильность работы вашего кода, выбрав рецепт, не имеющий отзывов, и попытавшись найти строку, соответствующую этому рецепту, в полученном `DataFrame`.

In [91]:
recipes.reset_index()

,id,name,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,44123,george s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,67664,healthy for them yogurt popsicles,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,38798,i can t believe it s spinach,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,35173,italian gut busters,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,84797,love is in the air beef fondue sauces,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...,...
29995,267661,zurie s holey rustic olive and cheddar bread,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
29996,386977,zwetschgenkuchen bavarian plum cake,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
29997,103312,zwiebelkuchen southwest german onion cake,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
29998,486161,zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN
29999,298512,cookies by design cookies on a stick,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

In [92]:
rec_rev_1 = recipes.merge(reviews, 
                        how = 'inner', 
                        left_on='id', 
                        right_on='recipe_id')

In [93]:
rec_rev_1.columns

Index(['name', 'minutes', 'contributor_id', 'submitted', 'n_steps',
       'description', 'n_ingredients', 'user_id', 'recipe_id', 'date',
       'rating', 'review'],
      dtype='object')

In [94]:
rec_rev_1 = rec_rev_1[['recipe_id','name','user_id','rating']]

In [104]:
rec_rev_1.rename(columns={'recipe_id':'id'})

            id                                    name  user_id  rating
0        44123   george s at the cove  black bean soup   743566       5
1        44123   george s at the cove  black bean soup    76503       5
2        44123   george s at the cove  black bean soup    34206       5
3        67664      healthy for them  yogurt popsicles   494084       5
4        67664      healthy for them  yogurt popsicles   303445       5
...        ...                                     ...      ...     ...
126691  486161                             zydeco soup   305531       5
126692  486161                             zydeco soup  1271506       5
126693  486161                             zydeco soup   724631       5
126694  486161                             zydeco soup   133174       5
126695  298512  cookies by design   cookies on a stick   804234       1

[126696 rows x 4 columns]

5.2 При помощи объединения таблиц и группировок, создайте `DataFrame`, состоящий из трех столбцов: `recipe_id`, `name`, `review_count`, где столбец `review_count` содержит кол-во отзывов, оставленных на рецепт `recipe_id`. У рецептов, на которые не оставлен ни один отзыв, в столбце `review_count` должен быть указан 0. Подтвердите правильность работы вашего кода, выбрав рецепт, не имеющий отзывов, и найдя строку, соответствующую этому рецепту, в полученном `DataFrame`.

In [105]:
rec_rev = recipes.merge(reviews, 
                        how = 'left', 
                        left_on='id', 
                        right_on='recipe_id')

In [106]:
rec_rev

,name,minutes,contributor_id,submitted,n_steps,description,n_ingredients,user_id,recipe_id,date,rating,review
0,george s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,743566.0,44123.0,2008-01-28,5.0,I lived in San Diego for 19 years and would g...
1,george s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,76503.0,44123.0,2003-06-03,5.0,This soup is the Bomb! Don't hesitate to try.....
2,george s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,34206.0,44123.0,2003-03-23,5.0,I just can't say enough about how wonderful th...
3,healthy for them yogurt popsicles,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,494084.0,67664.0,2012-09-26,5.0,These are great! I use 100% (organic) juice a...
4,healthy for them yogurt popsicles,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,303445.0,67664.0,2012-03-31,5.0,"Very, very good. My son loves these. He like..."
...,...,...,...,...,...,...,...,...,...,...,...,...
128591,zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,305531.0,486161.0,2013-07-18,5.0,Delish! I made this as directed but used a smo...
128592,zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,1271506.0,486161.0,2012-09-10,5.0,Now the only substitution I made was African B...
128593,zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,724631.0,486161.0,2014-01-07,5.0,"Very tasty soup, moderate spiciness (even afte..."
128594,zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,133174.0,486161.0,2013-07-18,5.0,Very yummy indeed. A spicy sausage was used i...
128595,cookies by design cookies on a stick,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0,804234.0,298512.0,2008-05-02,1.0,I would rate this a zero if I could. I followe...

In [107]:
rec_rev.columns

Index(['name', 'minutes', 'contributor_id', 'submitted', 'n_steps',
       'description', 'n_ingredients', 'user_id', 'recipe_id', 'date',
       'rating', 'review'],
      dtype='object')

In [108]:
rec_rev = rec_rev[['recipe_id','name','review']]

In [109]:
rec_rev.fillna(0).drop_duplicates()

,recipe_id,name,review
0,44123.0,george s at the cove black bean soup,I lived in San Diego for 19 years and would g...
1,44123.0,george s at the cove black bean soup,This soup is the Bomb! Don't hesitate to try.....
2,44123.0,george s at the cove black bean soup,I just can't say enough about how wonderful th...
3,67664.0,healthy for them yogurt popsicles,These are great! I use 100% (organic) juice a...
4,67664.0,healthy for them yogurt popsicles,"Very, very good. My son loves these. He like..."
...,...,...,...
128591,486161.0,zydeco soup,Delish! I made this as directed but used a smo...
128592,486161.0,zydeco soup,Now the only substitution I made was African B...
128593,486161.0,zydeco soup,"Very tasty soup, moderate spiciness (even afte..."
128594,486161.0,zydeco soup,Very yummy indeed. A spicy sausage was used i...
128595,298512.0,cookies by design cookies on a stick,I would rate this a zero if I could. I followe...

In [110]:
rec_rev.groupby(['recipe_id','name'])['review'].count().reset_index().sort_values(by=['review'], ascending=False).rename(columns={'review':'review_count'})

,recipe_id,name,review_count
1776,27208.0,to die for crock pot roast,1382
5812,82102.0,kittencal s moist cheddar garlic oven fried ch...,708
9695,135350.0,fannie farmer s classic baked macaroni cheese,674
7751,107786.0,beth s melt in your mouth barbecue ribs oven,591
3506,50719.0,the sweetest blueberry muffins,486
...,...,...,...
19255,296171.0,ranch chicken fajitas,1
11395,162060.0,eggplant aubergine crepes with spinach fi...,1
19258,296231.0,yum yum avocado salsa,1
19259,296234.0,mini mascarpone cheesecakes,1
7068,98745.0,my kids favorite goulash,1

5.2 При помощи объединения таблиц и группировок, создайте `DataFrame`, состоящий из трех столбцов: `recipe_id`, `name`, `review_count`, где столбец `review_count` содержит кол-во отзывов, оставленных на рецепт `recipe_id`. У рецептов, на которые не оставлен ни один отзыв, в столбце `review_count` должен быть указан 0. Подтвердите правильность работы вашего кода, выбрав рецепт, не имеющий отзывов, и найдя строку, соответствующую этому рецепту, в полученном `DataFrame`.

5.3. Выясните, рецепты, добавленные в каком году, имеют наименьший средний рейтинг?

In [119]:
rec_rev_2 = recipesDT.merge(reviews, 
                        how = 'left', 
                        left_on='id', 
                        right_on='recipe_id')

In [120]:
rec_rev_2

,name,minutes,contributor_id,submitted,n_steps,description,n_ingredients,user_id,recipe_id,date,rating,review
0,george s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,743566.0,44123.0,2008-01-28,5.0,I lived in San Diego for 19 years and would g...
1,george s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,76503.0,44123.0,2003-06-03,5.0,This soup is the Bomb! Don't hesitate to try.....
2,george s at the cove black bean soup,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,34206.0,44123.0,2003-03-23,5.0,I just can't say enough about how wonderful th...
3,healthy for them yogurt popsicles,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,494084.0,67664.0,2012-09-26,5.0,These are great! I use 100% (organic) juice a...
4,healthy for them yogurt popsicles,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,303445.0,67664.0,2012-03-31,5.0,"Very, very good. My son loves these. He like..."
...,...,...,...,...,...,...,...,...,...,...,...,...
128591,zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,305531.0,486161.0,2013-07-18,5.0,Delish! I made this as directed but used a smo...
128592,zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,1271506.0,486161.0,2012-09-10,5.0,Now the only substitution I made was African B...
128593,zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,724631.0,486161.0,2014-01-07,5.0,"Very tasty soup, moderate spiciness (even afte..."
128594,zydeco soup,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,133174.0,486161.0,2013-07-18,5.0,Very yummy indeed. A spicy sausage was used i...
128595,cookies by design cookies on a stick,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0,804234.0,298512.0,2008-05-02,1.0,I would rate this a zero if I could. I followe...

In [130]:
a = rec_rev_2.groupby(rec_rev_2['submitted'].dt.year)['rating'].mean().to_frame().reset_index().sort_values(by='rating')

In [131]:
a

    submitted    rating
18       2017  2.750000
19       2018  3.388889
17       2016  3.538462
16       2015  4.207317
0        1999  4.274895
..        ...       ...
7        2006  4.416310
8        2007  4.420073
4        2003  4.439152
5        2004  4.463778
15       2014  4.538235

[20 rows x 2 columns]

In [142]:
a['submitted'].iloc[0]

2017

### Сохранение таблиц `pd.DataFrame`

6.1 Отсортируйте таблицу в порядке убывания величины столбца `name_word_count` и сохраните результаты выполнения заданий 3.1-3.3 в csv файл.

In [ ]:
a = recipes.sort_values(by='name_word_count')

6.2 Воспользовавшись `pd.ExcelWriter`, cохраните результаты 5.1 и 5.2 в файл: на лист с названием `Рецепты с оценками` сохраните результаты выполнения 5.1; на лист с названием `Количество отзывов по рецептам` сохраните результаты выполнения 5.2.

#### [версия 2]
* Уточнены формулировки задач 1.1, 3.3, 4.2, 5.1, 5.2, 5.3